-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 17:07:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema abc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `abc` ;

-- -----------------------------------------------------
-- Schema abc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abc` DEFAULT CHARACTER SET utf8 ;
USE `abc` ;

-- -----------------------------------------------------
-- Table `abc`.`Serveur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc`.`Serveur` (
  `idServeur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`idServeur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc`.`Table` (
  `numTable` INT NOT NULL,
  `idServeur` INT NULL,
  PRIMARY KEY (`numTable`),
  CONSTRAINT `fk_Table_Serveur`
    FOREIGN KEY (`idServeur`)
    REFERENCES `abc`.`Serveur` (`idServeur`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Table_Serveur_idx` ON `abc`.`Table` (`idServeur` ASC);


-- -----------------------------------------------------
-- Table `abc`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc`.`Commande` (
  `numCommande` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `idServeur` INT NOT NULL,
  `numTable` INT NOT NULL,
  PRIMARY KEY (`numCommande`),
  CONSTRAINT `fk_Commande_Serveur`
    FOREIGN KEY (`idServeur`)
    REFERENCES `abc`.`Serveur` (`idServeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Table`
    FOREIGN KEY (`numTable`)
    REFERENCES `abc`.`Table` (`numTable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Commande_Serveur_idx` ON `abc`.`Commande` (`idServeur` ASC);

CREATE INDEX `fk_Commande_Table_idx` ON `abc`.`Commande` (`numTable` ASC);


-- -----------------------------------------------------
-- Table `abc`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc`.`Produit` (
  `refProduit` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `prixUnitaire` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`refProduit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc`.`Composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc`.`Composition` (
  `numCommande` INT NOT NULL,
  `refProduit` INT NOT NULL,
  `quantite` DECIMAL(5,3) NOT NULL,
  PRIMARY KEY (`numCommande`, `refProduit`),
  CONSTRAINT `fk_Commande_has_Produit_Commande1`
    FOREIGN KEY (`numCommande`)
    REFERENCES `abc`.`Commande` (`numCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Produit_Produit1`
    FOREIGN KEY (`refProduit`)
    REFERENCES `abc`.`Produit` (`refProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Composition_Produit_idx` ON `abc`.`Composition` (`refProduit` ASC);

CREATE INDEX `fk_Composition_Commande_idx` ON `abc`.`Composition` (`numCommande` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
